server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: reviewer
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2